# Generated by Django 2.2.5 on 2019-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresqlSettings',
            fields=[
                ('label_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dbname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=150)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
